ALTER TABLE "ai_golden_set_runs"
  ADD COLUMN IF NOT EXISTS "tool_accuracy" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "regression_detected" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "release_gate_pass" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "ai_golden_set_items"
  ADD COLUMN IF NOT EXISTS "expected_tools" JSONB,
  ADD COLUMN IF NOT EXISTS "actual_tools" JSONB,
  ADD COLUMN IF NOT EXISTS "tool_match" BOOLEAN,
  ADD COLUMN IF NOT EXISTS "tool_score" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "trace_score" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "trace_grade" TEXT,
  ADD COLUMN IF NOT EXISTS "scenario" TEXT,
  ADD COLUMN IF NOT EXISTS "trace_id" TEXT;
